In [51]:
!python pose.py -i test.mp4

[debug] test_24.txt: [0, 207, 61, 508]
(301, 61, 3)
(301, 61, 3)
(301, 61, 3)
[debug] test_25.txt: [0, 193, 128, 516]
(323, 128, 3)
(323, 128, 3)
117.78651387052554
(323, 128, 3)
[debug] test_26.txt: [4, 191, 192, 510]
(319, 188, 3)
(319, 188, 3)
94.6660797835365
(319, 188, 3)
[debug] test_27.txt: [86, 198, 245, 515]
(317, 159, 3)
(317, 159, 3)
117.34209553204232
(317, 159, 3)
[debug] test_28.txt: [53, 254, 402, 541]
(287, 349, 3)
(287, 349, 3)
173.98248575583958
(287, 349, 3)
[debug] test_28.txt: [137, 192, 307, 511]
(319, 170, 3)
(319, 170, 3)
161.08658672165143
(319, 170, 3)
[debug] test_29.txt: [198, 194, 373, 515]
(321, 175, 3)
(321, 175, 3)
127.19430326791799
(321, 175, 3)
[debug] test_30.txt: [155, 277, 540, 544]
(267, 385, 3)
(267, 385, 3)
178.95942184529343
(267, 385, 3)
[debug] test_30.txt: [261, 194, 435, 513]
(319, 174, 3)
(319, 174, 3)
(319, 174, 3)
[debug] test_31.txt: [237, 276, 569, 544]
(268, 332, 3)
(268, 332, 3)
(268, 332, 3)
[debug] test_31.txt: [323, 194, 494, 507]

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.


In [21]:
!set http_proxy=http://127.0.0.1:7890
!set https_proxy=http://127.0.0.1:7890


In [26]:
import cv2

frame = cv2.imread('input.jpg')
frame = cv2.resize(frame, (0, 0), fx=8, fy=8, interpolation=cv2.INTER_CUBIC)
cv2.imwrite('output.jpg', frame)

True

In [45]:
import numpy as np

frame = np.array(
    [[[1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]],
    [[1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]],
    [[1, 1, 1], [1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]],
    [[1, 1, 1], [1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]],
    [[1, 1, 1], [1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]]]
)

xyxy = [2, 2, 5, 5]

sub_frame = np.array(
    [[[20, 20, 20], [30, 30, 30], [40, 40, 40]],
    [[20, 20, 20], [30, 30, 30], [40, 40, 40]],
    [[20, 20, 20], [30, 30, 30], [40, 40, 40]]]
)

def drawSubFrame2(frame, sub_frame, xyxy):
    a, b, c = frame.shape
    x1, y1, x2, y2 = xyxy
    row_list = []
    for j in range(0, y1):
        row_list.append(frame[j].reshape(1, b, c))
    for j in range(y1, y2):
        left = frame[j][:x1]
        middle = sub_frame[j-y1]
        right = frame[j][x2+1:]

        row = np.concatenate([left, middle, right], axis=0)
        # print(row)
        row_list.append(row.reshape(1, b, c))
    for j in range(y2, frame.shape[0]):
        row_list.append(frame[j].reshape(1, b, c))
    return np.concatenate(row_list, axis=0)

def getSubFrame2(frame, xyxy):
    x1, y1, x2, y2 = xyxy
    row_list = []
    for j in range(y1, y2):
        row = frame[j][x1:x2]
        b, c = row.shape
        row_list.append(row.reshape(1, b, c))
    return np.concatenate(row_list, axis=0)

sub_frame = getSubFrame2(frame, xyxy)

print(sub_frame)

[[[2 2 2]
  [3 3 3]
  [4 4 4]]

 [[2 2 2]
  [3 3 3]
  [4 4 4]]

 [[2 2 2]
  [3 3 3]
  [4 4 4]]]
